
SPOOL c:\LST\INVALID.LST
SET ECHO OFF
SET SERVEROUTPUT OFF
SET TERMOUT OFF
SET HEAD OFF
SET PAGESize
SET FEEDBACK OFF
---- INVALID OBJECTS ----
SELECT object_type,object_name
FROM USER_OBJECTS
WHERE status = 'INVALID'
ORDER BY object_type;
SPOOL OFF
SET ECHO ON
SET TERMOUT ON
SET HEAD ON
SET FEEDBACK ON
SET SERVEROUTPUT ON


