set head off
set pagesize 50000
set feedback off
SPOOL D:\TESTSCRIPT\TRUNCATE.SQL

SELECT 'TRUNCATE TABLE '||OBJECT_NAME||' ;'
FROM USER_OBJECTS
WHERE OBJECT_TYPE='TABLE'
AND OBJECT_NAME NOT LIKE 'JBPM%'
ORDER BY LAST_DDL_TIME;

SPOOL OFF
@D:\TESTSCRIPT\truncate.sql