insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AF', 'AFGHANISTAN ', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AX', 'ÅLAND ISLANDS', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AL', 'ALBANIA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('DZ', 'ALGERIA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AS', 'AMERICAN SAMOA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AD', 'ANDORRA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AO', 'ANGOLA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AI', 'ANGUILLA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AQ', 'ANTARCTICA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AG', 'ANTIGUA AND BARBUDA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AR', 'ARGENTINA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AM', 'ARMENIA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AW', 'ARUBA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AU', 'AUSTRALIA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AT', 'AUSTRIA', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('CK', 'COOK ISLANDS
', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('CD', 'CONGO', 'N');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('CR', 'COSTA RICA
', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('AZ', 'AZERBAIJAN', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('BS', 'BAHAMAS', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('BH', 'BAHRAIN', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('BD', 'BANGLADESH', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('BB', 'BARBADOS', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('BY', 'BELARUS', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('BE', 'BELGIUM', 'Y');

insert into ope_country_defn (COUNTRY_ID, COUNTRY_NAME, AVAILABLE)
values ('BZ', 'BELIZE', 'Y');

