/********************************************************************************************
 * Copyright 2006 IDEAL INVENT Technologies Pvt. Ltd.                                       *
 * IDEAL INVENT Technologies Pvt. Ltd reserves all rights in the Program as delivered.      *
 * The Program or any portion thereof may not be reproduced in any form whatsoever except   *
 * as provided by license without the written consent of IDEAL INVENT Technologies Pvt. Ltd.*
 *																							*
 * File Name                   : AgreementRuntimeException.java                             *
 * Author                      : Manjunath N G                                              *
 * Creation Date               : 24-July-2008                                               *
 * Description                 : Parent class for all runtime exceptions generated by		*
 * 								ProcessMate application								        *
 * Modification History        :                                                            *
 *																						    *
 *     Version No.               Date               Brief description of change             *
 *  --------------------------------------------------------------------------------------- *
 *                       |                  |											    *
 *                       |                  |											    *
 *  --------------------------------------------------------------------------------------- *
 ********************************************************************************************/
package com.dnb.agreement.exception;

/**
 * Parent class for all Runtime exceptions that can be generated within our
 * applications
 */
public class AgreementRuntimeException extends RuntimeException {
	/** Reference to error code */
	private String errCode;

	/**
	 * Create a new runtime exception
	 * 
	 * @param errorCode
	 *            Detailed error code (should be found in IErrorCodes and in and
	 *            localized error messages file)
	 * @param message
	 *            Human-readable message (will appear in logs)
	 */
	public AgreementRuntimeException(String errorCode, String message) {
		super(message);
		this.errCode = errorCode;
	}

	/**
	 * Wrap a lower-level exception in a MdcRuntimeException
	 * 
	 * @param errorCode
	 *            Detailed error code (should be found in IErrorCodes and in
	 *            localized errormessages file)
	 * @param message
	 *            Human-readable message (will appear in logs)
	 * @param cause
	 *            Root cause of this exception
	 */
	public AgreementRuntimeException(String errorCode, String message, Exception cause) {
		super(message, cause);
		this.errCode = errorCode;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see mdc.exception.ErrorCodeException#getErrorCode()
	 */
	public String getErrorCode() {
		return errCode;
	}
}
